### ISSUE TITLE
@context checking too restrictive/false

### ISSUE THREAD

**Issue by danielpeintner** [thingweb/thingweb-playground#42]
Hi,

some examples that fail

Example 1
```
"@context": {
		"iot": "http://iotschema.org/"
}
```
Message: data['@context'] should be array, data['@context'] should be string, data['@context'] should be equal to one of the allowed values, data['@context'] should match exactly one schema in oneOf

Example 2

`"@context": [{"iot": "http://example.org/iot"}]`

Failure Message: > data['@context'][0] should be string, data['@context'][0] should be equal to one of the allowed values, data['@context'] should contain a valid item, data['@context'] should be string, data['@context'] should be equal to one of the allowed values, data['@context'] should match exactly one schema in oneOf

The assumption seems to be that it is always in the following way

```
"@context": ["http://www.w3.org/ns/td",
                {"iot": "http://example.org/iot"}]
```

Even the order seems to count... for example changing the order gives an error for

`"@context": [{"iot": "http://example.org/iot"}, "http://www.w3.org/ns/td"]`

"http://www.w3.org/ns/td" needs to come first to be valid.. i don't think these restrictions are necessary

**Comment by egekorkan** [comment]
So first of all, I think we are notifying Mr. @ context when we write `@context` outside of code quotes :smile: 
Then, the first example should be allowed since if we are extending the TD with more contexts, the default context should be there.
Then, I am not sure how the dereferencing would work if `@context` is an object because we would have to write something like `td:"http://www.w3.org/ns/td"`

Changing the order doesn't have any effect on me but now I have noticed a new issue where I get jsonld.ProcessingModeConflict: @version: 1.1 not compatible with json-ld-1.0 when I use additional contexts

**Comment by vcharpenay** [comment]
I also don't get an error when I change the order of items in the `@context` array. Some remarks:

> Then, I am not sure how the dereferencing would work if `@context` is an object because we would have to write something like `td:"http://www.w3.org/ns/td"`

In this case, they'd be no dereferencing at all because it is an _RDF prefix_ and not a JSON-LD context URI.

> "http://www.w3.org/ns/td" needs to come first to be valid.. i don't think these restrictions are necessary

I tend to agree. If the TD context is there, then there should also be an `@id` key at all levels (I'm working on the transformation script that should performs this operation). The JSON schema would become very complex if this restriction was to be included.

Btw, if you want to put a restriction on http://www.w3.org/ns/td, then it should appear _last_ in the `@context` array, so that it doesn't get overridden by subsequent definitions.

> I have noticed a new issue where I get jsonld.ProcessingModeConflict: @version: 1.1 not compatible with json-ld-1.0 when I use additional contexts

I can't reproduce the error but this should not be a problem in a near future (as soon as I finish specifying the transformation script to RDF).

**Comment by danielpeintner** [comment]
Mhh, the "order" error seems to be my fault. Very sorry!

w.r.t. the other points I am not sure now *what* is allowed and *what* not.
Also, I believe this needs to go into the TD spec. Don't you think @sebastiankb ?

**Comment by egekorkan** [comment]
I think this is solved now, please reopen if needed
