### ISSUE TITLE
Offline validation appears to be broken

### ISSUE THREAD

**Issue by mlagally** [thingweb/thingweb-playground#74]
I tried to use the offline version for validation both in Safari and Chrome.
The page loads, the "clear log" button works,
however the validate button does not perform any action.

**Comment by egekorkan** [comment]
This is a known "issue" that appears because of Chrome and Safari not allowing a web page to access system files. If you check the console, you will see the following message:

> Access to XMLHttpRequest at 'file:///home/eko/git/thingweb-playground/WebContent/td-schema.json' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https.
send @ jquery-2.2.3.js:4

So I don't know how to bypass this and make the validation still offline. I will add a text that warns against this but otherwise I am open for suggestions :)

**Comment by egekorkan** [comment]
@mlagally could you check if this is still the case and close the issue if it is?

**Comment by egekorkan** [comment]
Fixed via live server (a vs-code plugin) based serving of the index,html
